### PR TITLE
docs: Improve grammar, spelling and styling in README.md

### PR DESCRIPTION
**Pull request by MichaelCurrin**

### CODE REVIEW

**Comment by pellared** [comment]
@MichaelCurrin thanks a lot for the PR. I will merge changes from master to this branch and then merge this PR to master.

I am open to any suggestions

**Comment by MichaelCurrin** [comment]
I don't think that is necessary. You should be able to merge as is.

There are no conflicts with `master` and the only README.md change on `master` since I made my branch was adding a line to README.md

https://github.com/pellared/taskflow/commit/90b1a3979e2cb6664e9034132b181e5fa4cd9910#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R141

If you go to Settings for your repo, you can also require that a branch be up to date with master before merging it. This also adds a button to the end of the PR to pull in master into the branch - that is really easy to follow.

**Comment by MichaelCurrin** [comment]
The downside is that is not a linear history. I don't like pulling in master to a feature branch.

I prefer to rebase locally and fix any conflicts.

```sh
git checkout feature
git pull --rebase origin master
git push --force
```

That might work across forks too since as a maintainer you have edit access to my branch

**Review by pellared — APPROVED** [review]
LGTM 🚀

**Pull request merged**
